### PR TITLE
Split Image Links

### PR DESCRIPTION
**Pull request by CannonLock**
Split the intro image and added links to the appropriate sites

### CODE REVIEW

**Comment by bbockelm** [comment]
Since it's hard to visualize the SVG -- can you post screenshots of the before / after of the change?

**Comment by CannonLock** [comment]
Visually there is no change. The previous version had both logos in one svg, now they are split into two with each linking to their respective websites.

**Comment by bbockelm** [comment]
Ok, merging to get this going forward -- screenshots always help though!

**Comment by CannonLock** [comment]
@bbockelm Sounds good, is there anything you would have preferred I screenshotted here or should I add them for all visual changes going forward?

**Comment by bbockelm** [comment]
No need to backtrack on this one - just useful going forward.

**Pull request merged**
