### PR TITLE
Add Stathas bio to team request

### PR DESCRIPTION
**Pull request by jstathas**

### CODE REVIEW

**Comment by jstathas** [comment]
Added stathas image with reduced size

**Comment by djw8605** [comment]
Now there are 2 files, a jpeg file, and jpg file in the pull request.  Thanks for adding the smaller image though.

**Comment by jstathas** [comment]
First Timer. I will rename the image and commit again.

**Comment by djw8605** [comment]
No worries about it being the first time.  It still looks like there are 2 files.  I am more than willing to fix it for you.  But if you would like to do it, you will need to do a `git rm` one of the images (or, however you are adding/removing files to the repo).

**Comment by jstathas** [comment]
I'm sorry, I do not know how to do a git rm on the images. I did rename the image from .jpeg to .jpg. I think you should see it in the commits. I'd be happy if you take it from there.

**Comment by djw8605** [comment]
Merged.  It may take a minute for the website to update.

**Comment by jstathas** [comment]
Thank you!

________________________________

**Pull request merged**
