### PR TITLE
Adding News article re Covid Genetic Sequencing

### PR DESCRIPTION
**Pull request by jstathas**
News article genetic sequencing

### CODE REVIEW

**Review by djw8605 — CHANGES_REQUESTED** [review]
HI Janet,

A couple things:
- The top doesn't look right.  The header in the [PATH Awarded](https://raw.githubusercontent.com/path-cc/path-cc.github.io/master/_news/2020-10-20-path-awarded.md) article is on multiple lines.  It needs to look like that.
- You don't need to have the whole article in a `<p>` tag.  That will likely stop markdown from processing the file correctly.

**Comment by jstathas** [comment]
Make Revisons requested by Derek

**Comment by djw8605** [comment]
You need the 3 dashes above and below the header ("front matter" is the technical name).

**Comment by jstathas** [comment]
I added the front matter -

**Comment by jstathas** [comment]
OMG - i hope I have it all set now

________________________________

**Review by djw8605 — APPROVED** [review]
LGTM

**Pull request merged**
