### PR TITLE
Update 2022-All-Hands-Meeting.md

### PR DESCRIPTION
**Pull request by hannahcheren**
Updated the Registration section and added fee detail to the Fees section.

### CODE REVIEW

**Comment by osg-cat** [comment]
To be clear: No AHM announcement should go live until Janet or I give the ok.

**Review by CannonLock — APPROVED** [review]
LGTM -- Built locally and looked through Page

**Comment by CannonLock** [comment]
Screen Shot 2022-02-03 at 1 42 17 PM
2265/152416942-9a1289b4-306a-4fe7-9e98-4608e967921d.png">

**Comment by jstathas** [comment]
Updating event now that registration is open

**Comment by osg-cat** [comment]
I know this is merged already, but for the record: I’m not a big fan of duplicating a ton of information from the authoritative AHM site. What happens when we update that site? Does anyone remember to hunt down all the copies?

**Comment by CannonLock** [comment]
@osg-cat That is a great thought. I will put some thought into trying to get things like this localized to only one file we have to edit.

**Comment by osg-cat** [comment]
Hm. Not quite what I meant, but ok. I would be fine if people had to click once more… not the end of the world.

**Pull request merged**
