### PR TITLE
Add Todd L Miller.

### PR DESCRIPTION
**Pull request by Todd-L-Miller**

### CODE REVIEW

**Review by djw8605 — CHANGES_REQUESTED** [review]
Could you reduce the size of your picture.  In the end, 100x100 (or whatever dimensions preserve the aspect ratio) is all that is required.

**Comment by Todd-L-Miller** [comment]
PNG shrunk.

**Comment by djw8605** [comment]
It's still 261KB.  We're aiming at below 100KB.  Maybe you could reduce the size of the PNG to less than 100px in either width or depth.

**Comment by Todd-L-Miller** [comment]
Fully a third of the files in that directory are already > 100KB.  I'll see what more I can convince the limited photo-editing tools I have available to do, but if you want consistency, you have some work to do.

**Comment by djw8605** [comment]
Do you have the most up to date version of the git repo?  When I do a `ls -lh`, there is only 1 file > 100KB, pascal's picture at 102KB.

**Pull request merged**
