### PR TITLE
Update index.md

### PR DESCRIPTION
**Pull request by jstathas**
Addition to opening text to add link to registration page.

### CODE REVIEW

**Comment by jstathas** [comment]
Additon of link to Register for Open Science Grid on index page

**Comment by jstathas** [comment]
I do want this change deployed.

**Comment by djw8605** [comment]
Would you rather have it like a button that says "Sign Up" or something like that?

**Comment by jstathas** [comment]
Hi Derek,


Only if I do it myself. Let's deploy without the button for now.


Janet

________________________________

**Pull request merged**
