### PR TITLE
Add sidebar

### PR DESCRIPTION
**Pull request by djw8605**
Strawman to critique:

image

### CODE REVIEW

**Comment by bbockelm** [comment]
I like it!  I guess my only request is whether we should eat up a bit of the margins (not all of them!) on wider displays.

**Comment by djw8605** [comment]
That implies you want to undo the default bootstrap width?

**Comment by bbockelm** [comment]
Hm - is that from bootstrap itself?  I had assumed it was from the theme.

I'm reluctant to dig inside bootstrap at this point.  In that case, I'm fine as-is.

**Comment by djw8605** [comment]
Yes, I confirmed.  It's from boostrap, and it's the same width as the iris-hep website.

**Comment by jstathas** [comment]
I like the right 1/3 gutter, but I still really think it needs to be pushed down with the opening hero image and title spanning the width of the screen  - so the first view isn't so busy. Lauren is also going to be asking for the events above the twitter....i.e. no good deed goes unpunished.

**Comment by djw8605** [comment]
@jstathas I agree with all of the above.  For now, small iterations.  The events will take a bit of time to implement.  And indeed, the twitter was just really fast to do (very little changes required).

**Pull request merged**
