### PR TITLE
Rewrite the intro to the PATh facility

### PR DESCRIPTION
**Pull request by bbockelm**
Particularly, this includes a stronger, HTC-centric approach and leaves the "hardware details" to later.

### CODE REVIEW

**Comment by bbockelm** [comment]
@CannonLock - can you check the failed links?

**Comment by bbockelm** [comment]
Offline review comments from @tannenba:

- "...a wider variety off sites."   should be "...a wider variety of sites."
- "Users of the facility will receive credit accounts..."  - the 'credit accounts' link is dead, and probably should go to a different page anyway
- May want to point out that single-node MPI jobs are ok.
- When stating "a large number of individual batch jobs", may want to also give some time idea...  "individual batch jobs that run anywhere from a few minutes to many days". 
- May help to give a specific examples of common HTC workloads.  E.g. An example of an ideal HTC workloads includes parameter sweeps, processing of thousands of data sets where each data set can be processed by an independent job, ....

All seem reasonable to me.  Will adjust.

**Comment by CannonLock** [comment]
@bbockelm Couple new links popped up, but it looks like they are all fixed now.

**Comment by bbockelm** [comment]
Given the offline review from Todd, I'm going to self-merge on this.

**Pull request merged**
