### PR TITLE
Updating the Logos

### PR DESCRIPTION
**Pull request by CannonLock**
Changed out the Logos for the new ones. This included a webpage reorder.

### CODE REVIEW

**Comment by CannonLock** [comment]
[
Screen Shot 2021-06-07 at 11 31 48 AM
](url)

**Comment by bbockelm** [comment]
Don't particularly like all those logos piled up.  Maybe move the CHTC and OSG one down below the OSG Connect box in light red?

**Comment by CannonLock** [comment]
Screen Shot 2021-06-08 at 10 25 35 AM
Screen Shot 2021-06-08 at 10 24 24 AM

**Comment by bbockelm** [comment]
@CannonLock - have some merge conflicts currently.

**Pull request merged**
