### PR TITLE
Addition of CC * support to index text

### PR DESCRIPTION
**Pull request by jstathas**
Adding CC* text, but no banner

### CODE REVIEW

**Comment by jstathas** [comment]
Tim, This CC Star text does not have any banner html or bolding. I can review bootstrap coding options to update CSS if you want, but I'd prefer to get a test environment set up first since I'll be out of my skill set a bit.

**Review by osg-cat — COMMENTED** [review]
This file is (nominally) Markdown — why use all the HTML? Nothing jumped out at me as being necessarily in HTML.

**Comment by lmichael107** [comment]
Perhaps Janet is less familiar with Markdown, and we could show her to a cheatsheet (https://github.com/adam-p/markdown-here/wiki/Markdown-Cheatsheet) or help her translate what she's written in HTML to Markdown format? -Lauren

**Comment by jstathas** [comment]
Tim and Lauren,


Thank you - the Markdown cheatsheet will be very helpful. I had seen Derek W look up Bootstrap when making updates to the site - so I actually thought that was what it was using. I have some familiarity with Bootstrap  - we used that in our application in my former life, but none with Markdown.


Janet

________________________________

**Comment by osg-cat** [comment]
I’m going to close this PR without merging, because the solution that I came up with tries to co-exist with Jekyll and Bootstrap in different ways. I kept the text content, though, with only the smallest of changes. See my forthcoming PR for the whole mess. I won’t merge mine, so we can always close it and come back to this one!

**Pull request closed without merging**
